### ISSUE TITLE
[Preview Build] Esbuild error when using ScriptKit

### ISSUE THREAD

**Issue by mattpocock** [johnlindquist/kit#1335]
Running 194.7. Appears that the incorrect `esbuild` package is installed.

Error:

You installed esbuild for another platform than the one you're currently using.
This won't work because esbuild is written with native code and needs to
install a platform-specific binary executable.

Specifically the "@esbuild/android-arm64" package is present but this platform
needs the "@esbuild/darwin-arm64" package instead. People often get into this
situation by installing esbuild on Windows or macOS and copying "node_modules"
into a Docker image that runs Linux, or by copying "node_modules" between
Windows and WSL environments.

<img width="766" alt="image" src="https://github.com/johnlindquist/kit/assets/28293365/ba18f751-bc13-45cf-aaf6-af090573a47e">

**Comment by johnlindquist** [comment]
@mattpocock 

This usually occurs when people "npm install" packages to Kenvs from the command line instead of using the included ~/.knode/bin/npm

Try these 3 things (each one might fix it):

1. Re-link kit to kenv:

Quit Kit.app
In a terminal:
```
cd ~/.kenv
~/.knode/bin/npm i ~/.kit
```
Open Kit.app

2. Re-install the SDK
Quit Kit.app
Delete ~/.kit
Open Kit.app to let it re-install the SDK


3. Manually remove esbuild
Check ~/.kenv/node_modules for esbuild and delete it. You can also rm -rf the node_modules in the kenv and run:

```
cd ~/.kenv
~/.knode/bin/npm i
```

**Comment by mattpocock** [comment]
Nice, 2 fixed it. Thanks @johnlindquist!
