### ISSUE TITLE
Extra space breaks clipboard expected behaviour of the Clipboard #v2

### ISSUE THREAD

**Issue by joeyvandijk** [johnlindquist/kit#1417]
When using ScriptKit 2.2.8 on macos Sonoma 14.2.1 I noticed that since v2 the clipboard history (open Scriptkit > type `C` > type `Enter`) did not work anymore ❌. It kept showing me a list 

![Screenshot 2024-01-03 at 11 11 33](https://github.com/johnlindquist/kit/assets/3379812/2c22317a-8c88-4c48-a873-b555dee72382)

while I noticed that in the input field a `space` existed and therefore I got the same results everytime.
When removing the `space` with clicking `backspace` I got

![Screenshot 2024-01-03 at 11 11 48](https://github.com/johnlindquist/kit/assets/3379812/76a1f734-2adc-4a99-bec9-15dfc6f35191)

which worked as expected. ✅

I suppose after the shortcut keyword `c` the input field get an empty space that should be removed to ensure expected behaviour for the clipboard (at least on Mac) again.

**Comment by johnlindquist** [comment]
@joeyvandijk Oh, I see:

`c` is a "keyword" and keyword behaviors are triggered by the keyword then a spacebar. So typing: `c` then `space` will bring up the clipboard history and allow you to press `delete` to remove the keyword and go back to the main menu.

If you want to patch this, you can run this script:

```js
// Name: Fix Clipboard

import "@johnlindquist/kit"

await replace({
  files: kitPath("main", "clipboard-history.js"),
  from: "input: keyword + ` `",
  to: "input: keyword ? keyword + ` ` : ``",
})
```
[install fix clipboard](https://scriptkit.com/api/new?name=fix-clipboard&url=https://gist.githubusercontent.com/johnlindquist/175c4d63801897ae892c657e270cd77a/raw/7e0f4ef8d0c9decff07d62ca56278cad3991bbab/fix-clipboard.ts)

I'll get this truly fixed in the next release

**Comment by joeyvandijk** [comment]
I understand and a good fix for a new release. Thanks for now 👍
