### ISSUE TITLE
Add an url scheme for launching scripts from other apps

### ISSUE THREAD

**Issue by pomdtr** [johnlindquist/kit#363]
I would love to be able to trigger any kit script from outside using an URI.

Is there already a built-in way to achieve this? 
You mentioned launching your scripts from alfred in https://github.com/johnlindquist/kit/discussions/56

A command-line utility launching a specific script's UI would also work for my use case.

Ex: `open kit://run?script=my-custom-script`

**Comment by pomdtr** [comment]
Ok the sk utility is perfect to achieve this :)

**Comment by johnlindquist** [comment]
@pomdtr I'm using url the scheme for installing scripts from ScriptKit.com. 

```bash
open "kit://hello-world?url=https://raw.githubusercontent.com/johnlindquist/shared-kenv/main/scripts/hello-world.js"
```

☝️ That would grab that file and name it "hello-world.js" in your kit environment (kenv).

I'm hesitant to allow the URL protocol to run any script because I'm worried it would get abused. I'm open to ideas of ways to make it safer.


## sk

It should just be `sk` then the `command` name of your script:
```bash
~/.kit/bin/sk book-search
```

(or just `sk book-search` if you `~/.kit/bin` is on your $PATH)

Does that not work for you? Do you see an error or any output?

**Comment by pomdtr** [comment]
Ok, it works perfectly thanks a lot!

**Comment by johnlindquist** [comment]
Closing this for now. Feel free to re-open if we can come up with scenarios where `sk` isn't good enough.
