### ISSUE TITLE
Multiple `exec` calls don't run

### ISSUE THREAD

**Issue by brandonpittman** [johnlindquist/kit#487]
## Expected

When running this script:

```ts
import "@johnlindquist/kit";

const open = (app: string) => exec(`open -a ${app}`);

open("Slack");
open("Discord");
```

I expect Slack to open, then Discord to open.

## Actual

Slack opens, but Discord does not.

## Memo

Switching the call order results in Discord opening, but not Slack.

**Comment by johnlindquist** [comment]
Hmm 🤔 thanks. Seems to work fine when invoked by the terminal, but something about the way the app invokes the script isn't working. I'll hunt it down!

**Comment by johnlindquist** [comment]
That script runs for me now. Closing, but let me know if you're still seeing the issue

**Comment by brandonpittman** [comment]
This also works for me as well now!

Is there any reason to use `exec` now though as `zx` is available?

**Comment by johnlindquist** [comment]
I prefer `exec`:

`exec` is now using https://github.com/sindresorhus/execa (with `shell` set to `true`) instead of shelljs.

api: https://github.com/sindresorhus/execa#execafile-arguments-options

`execa` has 36,601,997 weekly downloads, so I kind of "trust" it more for working with all scenarios than zx, especially since I'm concerned about Windows support.

## zx quotes are a "gotcha"

https://github.com/google/zx/blob/main/docs/quotes.md

Quotes are my biggest gripe with zx. Here's a comparison of what I consider the most common scenario for using exec/zx:

```js
let dir = "~/.kit"

// exec works as expected
let { stdout } = await exec(`ls ${dir}`)
console.log(stdout)

// zx fails because it converts the command to
// ls '$'~/.kit''
await $`ls ${dir}` // ls: $~/.kit: No such file or directory
```

So personally, I won't use or teach zx because then I'd have to explain the quotes every time. But that's just me.
