### ISSUE TITLE
Cannot select a choice with ENTER

### ISSUE THREAD

**Issue by carlesba** [johnlindquist/kit#612]
# Steps to reproduce

Using the [giphy-search](https://www.scriptkit.com/johnlindquist/giphy-search) script:

1. type a query
2. wait for results to appear
3. use arrow keys to select a choice
4. press enter
5. kit app disappears

expected
kit should show next list of choices

This works well when the choice is selected with the mouse. When choosing an option the next list of arguments appears.

Enter key also works well for top level list of scripts.

**Comment by johnlindquist** [comment]
@carlesba Good catch, I just released a build that should address this.

Please update to latest:
![CleanShot 2021-11-22 at 06 18 05](https://user-images.githubusercontent.com/36073/142868457-98605a43-8f17-4db6-b878-29449f86812d.png)

**Comment by johnlindquist** [comment]
## What happened:

I refactored some internals to enable `div` info that can "timeout":

```js
div(`Wait for 5 seconds`)
await wait(5000)
```

Because `div` is waiting for user input AKA "submit", `wait` must invoke `submit` if no input is received.

## Where the Refactor Broke

I used to use `wait` in part of the main prompt logic, but had to delete it since it now invokes `submit`. Thus the behavior you're seeing where the prompt wouldn't wait when trying to invoke a second prompt. This made it look like "Enter" wasn't working.

**Comment by carlesba** [comment]
Nice! that made the fix. 

Thank you very much :)
