### ISSUE TITLE
getTabs throw "Unexpected end of JSON input"

### ISSUE THREAD

**Issue by ValentinH** [johnlindquist/kit#662]
I'm trying to access the url of the current tab and faced issues when playing with the `getTabs()` function:
```
[2021-12-20 15:24:44.115] [warn]  SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at global.getTabs (file:///Users/valentin/.kit/lib/browser.js:62:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///Users/valentin/.kenv/.scripts/example.mjs:3:12
```

For example with this script taken from [this lesson](https://egghead.io/lessons/script-kit-save-chrome-tabs-in-a-markdown-file-and-take-notes-with-script-kit):
```ts
import "@johnlindquist/kit"

let tabs = await getTabs()

let tabsMd = tabs
  .map(tab => `* [${tab.title || tab.url}](${tab.url})`)
  .join("\n")

let notes = await editor(tabsMd)
```

I'm using Brave.

**Comment by johnlindquist** [comment]
On my phone, but I believe it's:

await getTabs("Brave")

It defaults to Chrome.

**Comment by ValentinH** [comment]
You are completely right, I thought it was defaulting to the default browser of the system.

**Comment by johnlindquist** [comment]
🤔 I'll have to see if it's possible to query for the default browser

**Comment by valeriashpiner** [comment]
@johnlindquist I am having the same error, when I pass anything as a parameter, but not "Google Chrome", for example:

`import "@johnlindquist/kit"

let tabs = await getTabs("Firefox")

let tabsMd = tabs
  .map(tab => `* [${tab.title || tab.url}](${tab.url})`)
  .join("\n")

let notes = await editor(tabsMd)

... more code`

Gives me the exact error: `SyntaxError: Unexpected end of JSON input`

**Comment by KiwiKilian** [comment]
I'm experiencing the same. Basically I'm trying to port [this script](https://www.scriptkit.com/johnlindquist/chrome-tab-open) to use `Firefox Developer Edition`.

For the line:
```js
let currentTabs = await getTabs("Firefox Developer Edition")
```

It throws:
```
[warn] SyntaxError: Unexpected end of JSON input
```

I also tried with `"Firefox"`, no luck either. In both cases, the browser will start if not already started. Might this be due to missing privacy automation allowances? Kit only lists "Google Chrome" there to check.

**Comment by timsun28** [comment]
I'm having the same issues as @KiwiKilian when I try to get the current tabs from a Firefox window. I have done some research and testing and found the following two sources that caught my attention:

https://bugzilla.mozilla.org/show_bug.cgi?id=125419
A 21-year-old bug report on Firefox to add basic AppleScript functionality. Apparently it hasn't been implemented and that's why it's not supported in Script Kit.

https://matthewbilyeu.com/blog/2018-08-24/getting-url-and-tab-title-from-firefox-with-applescript
This is a blog post from someone who wrote an AppleScript to get the current tab title and url through copy/paste. This is probably not a good use case for a getTabs function that needs to get all open tabs from all windows, but is interesting to read about. 

I guess the only thing we can do is wait and let the Firefox developers know that we would like AppleScript support in a future version. And for script kit to maybe add a warning/message that not all browser functions are compatible with Firefox.

**Comment by johnlindquist** [comment]
@KiwiKilian @timsun28 

I want to move away from AppleScript as much as possible. So my gameplan is to write a Chrome, Firefox, etc extension that can offer a bridge into Script Kit. A quick start would be something as simple as:

 "An extension that writes the current open tabs to a tabs.json"

Then Script Kit could read that file and we're back in business.

Any chance that's something you'd be interested in building?

**Comment by timsun28** [comment]
@johnlindquist 

That sounds interesting, and would also help with using the same extension for both windows, mac and possibly linux. 

Have you already planned out how you're going to trigger this write to a file functionality (for a browser/vscode)?
If Firefox doesn't have AppleScript support, how are you planning to trigger something within an extension?

I would be interested to look into this, I'll give it a go this week and see what I can come up with for Firefox in particular.

**Comment by johnlindquist** [comment]
@timsun28 So my hope is that extensions have events when tabs/urls change.

So the full functionality of the extension would be:

```
when tabs change -> write tabs.json
```

The Script Kit would only have to read the tabs.json file and wouldn't have to know anything about Firefox/Applescript/etc.

**Comment by johnlindquist** [comment]
@timsun28 It's also possible that Firefox creates a file/db somewhere on the system already. Chrome does this for bookmarks/history:

https://github.com/johnlindquist/kit/discussions/1041

But I haven't looked into Firefox at all

**Comment by timsun28** [comment]
@johnlindquist I've found that browser add-ons allow an extension to communicate between native apps using standard input/output on the app side of things to receive messages. I think this could be used to let script kit the app send a message to the browser extension for data and let the browser extension reply with the requested data. The only downside is that there seems to be quite a lot of differences between browsers and operating systems. But they are all well documented, so it shouldn't be too much of a problem.

Some pages that contain information about this protocol: 
[General info](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Working_with_files#process_files_in_a_local_app)
[App side of things](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging#app_side)
[Example using a python app](https://github.com/mdn/webextensions-examples/tree/main/native-messaging)
[My example GitHub repo for ScriptKit](https://github.com/timsun28/ScriptKit.demo.browser)

Could you let me know if you think this is a good approach for the given problem and if the Node.js example is something that could be implemented in ScriptKit app? 

The only thing I don't quite get is how the [.json](https://github.com/timsun28/ScriptKit.demo.browser/blob/main/app/script_kit.json) file works in the native app. It doesn't seem to need to be registered in a way.

**Comment by johnlindquist** [comment]
@timsun28 Wow, that could unlock a ton of cool stuff and definitely worth exploring 🤔

I still think the first step is to simply capture the current state (windows/tabs/urls) into a json file that a script could read.

Script Kit could even watch the json file for changes if you want to run a script any time the browser state changes.

To me, "browser state as a json file" just feels like a cross-platform, easy win that covers 90% of scenarios.

Then we could dive into sending messages between browser<->Script Kit and build out some really exciting workflows 🤯

**Comment by timsun28** [comment]
@johnlindquist Looking at the following [page](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Working_with_files) it seems like there is not really a good solution for writing to any file type. The only option I see is to write to the IndexedDB of the browser, but I'm not sure if IndexedDB is available outside the app to other native applications. 

And because Script Kit won't be directly communicating with the browser, you need to make sure that the .json file is always up-to-date. 

The JSON solution also doesn't allow for any future changes in terms of actions in the browser like switch to active tab, favourite a certain tab, delete history or any other actions that could be triggered from an extension. 

I will try to make a proof of concept that works with script kit and Firefox, so I could demonstrate how this could be further implemented in the app!
